from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from thesis_rl.curriculum.config import StageConfig
from thesis_rl.curriculum.state import CurriculumState


class CurriculumStrategy(Protocol):
    def get_current_stage(self) -> StageConfig: ...

    def get_env_config(self, evaluation: bool = False) -> dict[str, object]: ...

    def record_train_steps(self, num_steps: int) -> None: ...

    def record_eval_metrics(self, metrics: Mapping[str, float]) -> bool: ...

    def should_promote(self) -> bool: ...

    def promote(self) -> bool: ...

    def is_finished(self) -> bool: ...

    @property
    def state(self) -> CurriculumState: ...

    def load_state(self, state: CurriculumState) -> None: ...
