from __future__ import annotations

import csv
from pathlib import Path
from typing import Any


class CSVRecorder:
    """Append structured rows to run-scoped CSV files with fixed schemas."""

    SCHEMAS: dict[str, list[str]] = {
        "train_chunks.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "chunk_id",
            "stage",
            "stage_index",
            "steps_start",
            "steps_end",
            "global_step",
            "chunk_steps",
            "episodes",
            "ep_rew_mean",
            "ep_len_mean",
            "ep_success_rate",
            "ep_collision_rate",
            "ep_out_of_road_rate",
            "ep_route_completion_mean",
            "actor_loss",
            "critic_loss",
            "learning_rate",
            "n_updates",
            "fps",
            "elapsed_seconds",
        ],
        "evals.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "eval_id",
            "chunk_id",
            "stage",
            "stage_index",
            "global_step",
            "eval_episodes",
            "deterministic",
            "mean_reward",
            "std_reward",
            "mean_rule_saturation_max",
            "collision_rate",
            "collision_rate_std",
            "out_of_road_rate",
            "success_rate",
            "success_rate_std",
            "route_completion",
            "top_rule_violation_rate",
            "avg_error_value",
            "max_error_value",
            "counterexample_rate",
            "violated_rules_ratio",
            "unique_violation_patterns",
            "success_rate_min",
            "collision_rate_max",
            "out_of_road_rate_max",
            "top_rule_violation_rate_max",
            "route_completion_min",
            "gate_success_pass",
            "gate_collision_pass",
            "gate_out_of_road_pass",
            "gate_top_rule_pass",
            "gate_route_completion_pass",
            "passed_eval_gates",
            "consecutive_passes",
            "warmup_evals_required",
            "consecutive_evals_required",
            "promoted",
            "next_stage",
        ],
        "eval_episodes.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "eval_id",
            "episode_id",
            "stage",
            "stage_index",
            "global_step",
            "scenario_seed",
            "scenario_id",
            "deterministic",
            "reward",
            "episode_length",
            "success",
            "collision",
            "out_of_road",
            "timeout",
            "route_completion",
            "top_rule_violation_rate",
            "error_value",
            "violated_rules",
            "violation_pattern",
            "video_path",
        ],
        "promotions.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "event_type",
            "from_stage",
            "to_stage",
            "from_stage_index",
            "to_stage_index",
            "eval_id",
            "chunk_id",
            "global_step",
            "stage_steps_done",
            "stage_steps_min_required",
            "passed_eval_gates",
            "consecutive_passes",
            "success_rate",
            "collision_rate",
            "out_of_road_rate",
            "top_rule_violation_rate",
            "route_completion",
            "reason",
        ],
        "rule_metrics.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "eval_id",
            "chunk_id",
            "stage",
            "stage_index",
            "global_step",
            "rule_name",
            "rule_priority",
            "violated",
            "violation_rate",
            "violation_count",
            "mean_margin",
            "min_margin",
            "max_margin",
        ],
        "final_eval.csv": [
            "algorithm",
            "reward_mode",
            "curriculum_name",
            "seed",
            "run_id",
            "total_timesteps",
            "final_stage",
            "final_stage_index",
            "final_stage_reached",
            "final_eval_episodes",
            "deterministic",
            "mean_reward",
            "std_reward",
            "mean_rule_saturation_max",
            "collision_rate",
            "collision_rate_std",
            "out_of_road_rate",
            "success_rate",
            "success_rate_std",
            "route_completion",
            "top_rule_violation_rate",
            "avg_error_value",
            "max_error_value",
            "counterexample_rate",
            "violated_rules_ratio",
            "unique_violation_patterns",
        ],
    }

    def __init__(self, csv_dir: str | Path) -> None:
        self.csv_dir = Path(csv_dir)
        self.csv_dir.mkdir(parents=True, exist_ok=True)

    def append_row(self, filename: str, row: dict[str, Any]) -> None:
        if filename not in self.SCHEMAS:
            raise KeyError(f"Unsupported CSV schema: {filename}")

        path = self.csv_dir / filename
        fieldnames = self.SCHEMAS[filename]
        file_exists = path.exists()
        clean_row = {key: row.get(key) for key in fieldnames}

        with path.open("a", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames)
            if not file_exists:
                writer.writeheader()
            writer.writerow(clean_row)
